export const FETCH_BOOKS_START = "FETCH_BOOKS_START";
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
export const EDIT_BOOK_SUCCESS = "EDIT_BOOK_SUCCESS";
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
export const FILTER_BOOKS_SUCCESS = "FILTER_BOOKS_SUCCESS";

export const FETCH_GENRES_SUCCESS = "FETCH_GENRES_SUCCESS";
export const SUBMIT_GENRE = "SUBMIT_GENRE";
export const DELETE_GENRE = "DELETE_GENRE";
export const EDIT_GENRE = "EDIT_GENRE";

export const SET_MINIMUM_PRICE = "SET_MINIMUM_PRICE";
export const SET_MAXIMUM_PRICE = "SET_MAXIMUM_PRICE";
