export const FETCH_BOOKS_START =  'FETCH_BOOKS_START';
export const FETCH_BOOKS_SUCCESS =  'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAIL =  'FETCH_BOOKS_FAIL';
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
export const DELETE_BOOK_FAIL = 'DELETE_BOOK_FAIL';
export const EDIT_BOOK_SUCCESS = 'EDIT_BOOK_SUCCESS';
export const EDIT_BOOK_FAIL = 'EDIT_BOOK_FAIL';
export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS';
export const ADD_BOOK_FAIL = 'ADD_BOOK_FAIL'
export const FILTER_BOOKS_SUCCESS = 'FILTER_BOOKS_SUCCESS'
export const FILTER_BOOKS_FAIL = 'FILTER_BOOKS_FAIL'


export const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS';
export const FETCH_GENRES_FAIL = 'FETCH_GENRES_FAIL';
export const SUBMIT_GENRE = 'SUBMIT_GENRE'
export const DELETE_GENRE = 'DELETE_GENRE'


